
services:
  webserver_python:
    build: ./app
    container_name: geodjango_webserver_dev
    command: python3 hellodjango/manage.py runserver 0.0.0.0:8000
    networks:
      - geodjango_project_network_dev
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  postgis:
    image: postgis/postgis:latest
    container_name: geodjango_postgis_dev
    environment:
      - POSTGRES_DB=geodjango_database
      - POSTGRES_PASSWORD=dessert
      - POSTGRES_USER=dheerajchand
      - POSTGRES_HOST_AUTH_METHOD=password
    ports:
      - 54321:5432
    networks:
      - geodjango_project_network_dev
    volumes:
      - geodjango_pg_data:/var/lib/postgresql
    restart: always

  redis:
    image: redis:7
    container_name: geodjango_redis_server
    networks:
      - geodjango_project_network_dev

networks:
  geodjango_project_network_dev:
volumes:
  geodjango_pg_data: