
services:
  webserver_python:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: geodjango_webserver_prod
    command: sh -c "cd hellodjango/ && gunicorn hellodjango.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - geodjango_project_network_prod
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgis
  postgis:
    image: postgis/postgis:latest
    container_name: geodjango_postgis_prod
    env_file:
      - ./.env.prod.db
    ports:
      - 54321:5432
    networks:
      - geodjango_project_network_prod
    volumes:
      - geodjango_pg_data:/var/lib/postgresql
    restart: always
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - webserver_python
    networks:
      - geodjango_project_network_prod
    volumes:
      - static_volume:/home/app/web/staticfiles
networks:
  geodjango_project_network_prod:
volumes:
  geodjango_pg_data:
  static_volume:
